#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@usb_printer[-1]
	add ucitrack usb_printer
	set ucitrack.@usb_printer[-1].init=usb_printer
	commit ucitrack
EOF

# [ -f /etc/init.d/p910nd ] && /etc/init.d/p910nd disable
[ -f /usr/sbin/p910nd ] && ln -s /usr/sbin/p910nd /usr/sbin/p910md

exit 0
